# Generated by Django 4.2.7 on 2023-12-18 18:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_activity_delete_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='host',
        ),
        migrations.AddField(
            model_name='activity',
            name='action',
            field=models.CharField(default=api.models.generate_unique_code, max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='currency',
            field=models.CharField(default=api.models.generate_unique_code, max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='grossAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='settlementDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='symbol',
            field=models.CharField(default=api.models.generate_unique_code, max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='tradeDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
