# Generated by Django 4.2.7 on 2023-12-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_account_remove_activity_host_activity_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='symbolId',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='currency',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='symbol',
            field=models.CharField(default='', max_length=20),
        ),
    ]
