# Generated by Django 4.2.7 on 2023-12-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_activity_symbolid_alter_activity_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.DecimalField(decimal_places=0, default=0, max_digits=20, unique=True)),
                ('type', models.CharField(default='', max_length=20)),
                ('isPrimary', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_id',
        ),
        migrations.AddField(
            model_name='activity',
            name='accountNumber',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='lastModified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
