# Generated by Django 4.2.7 on 2023-12-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_account_remove_activity_activity_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='netAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
